language: node_js

node_js:
  - node

dist: trusty

cache:
  npm: true
  directories:
    - '$HOME/.sonar/cache'

# Trigger build only when one of the following conditions is met
if: type = pull_request OR branch = master OR tag IS present

addons:
  chrome: stable
  sonarcloud:
    organization: "ontotext-ad"
  # Needed for Cypress tests
  apt:
    packages:
      - libgconf-2-4

jobs:
  include:
    - stage: build and test
      if: type = pull_request
      script:
        - npm run test:coverage
        - npm run build
        - npm run sonar
        - npm run test:acceptance

      after_script:
        - npm run test:coveralls

    - stage: npm release
      if: tag IS present
      deploy:
        - provider: npm
          skip_cleanup: true
          email: $NPM_MAIL
          api_key: $NPM_TOKEN
          on:
            tags: true

        - provider: script
          # Workaround. cannot login in NPM and cannot configure NPM provider to go in the directory
          script: cd test-cypress/ && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && npm publish
          skip_cleanup: true
          on:
            tags: true
